### PR TITLE
update lab manual with name

### PR DESCRIPTION
**Pull request by anshpatel19**
added "Ansh Patel (2021)" to end of lab members section as part of onboarding process

### CODE REVIEW

**Review by jeremymanning — CHANGES_REQUESTED** [review]
Hi Ansh-- almost there!  You just need to run pdflatex another time (or two) in order to get the table of contents to show up.

**Comment by anshpatel19** [comment]
updated to fix table of contents

**Comment by anshpatel19** [comment]
changed name from incorrect section (lab alumni) to correct section (current lab members)

**Comment by jeremymanning** [comment]
looks great!

**Pull request merged**
