### PR TITLE
made a couple of grammar changes

### PR DESCRIPTION
**Pull request by cjun357**

### CODE REVIEW

**Comment by paxtonfitzpatrick** [comment]
hey @cjun357, thanks for the edits! Can you please recompile the PDF so the change appears in the rendered document?  After that, I'll merge in your changes and you'll be good to go!

**Comment by cjun357** [comment]
Hello,

Just to clarify, are you asking me to generate a new pdf file from my latex edits and then commit that to Github?

Sincerely,
Chris Jun
________________________________

**Comment by paxtonfitzpatrick** [comment]
@cjun357 Exactly 🙂  

If you commit and push the new PDF, it will be added to this pull request automatically.  Feel free to message me on Slack or shoot me an email if you have any questions about how to recompile the document, or if you run into any issues.

**Comment by cjun357** [comment]
[lab_manual_edit.pdf](https://github.com/ContextLab/lab-manual/files/4920534/lab_manual_edit.pdf)

**Comment by paxtonfitzpatrick** [comment]
hey @cjun357, so rather than uploading it as a comment, here's what you want to do:

1. make your edits to the raw source code in the `lab_manual.tex` file (you've already done this)
2. recompile `lab_manual.pdf` from the updated `.tex` file. You can either do this directly from the command line or use a TeX editor (I recommend using an editor; it's a lot easier). Page 5 of the lab manual has a [link](https://www.latex-project.org/get/) where you can download the right TeX distribution for your computer, as well as a link to a set of useful [tutorials](https://www.latex-tutorial.com/quick-start/) on using LaTeX.  
3. Once you recompile the PDF file, can check `git status` and you should see the `lab_manual.pdf` file has been changed.
4. `git add` and `git commit` the updated PDF, then `git push` it to your fork of the lab-manual GitHub repository ([cjun357/lab-manual](https://github.com/cjun357/lab-manual)). 

Because you have a pull request open with the main lab manual repo ([ContextLab/lab-manual](https://github.com/ContextLab/lab-manual)), the any new changes made to your fork ([cjun357/lab-manual](https://github.com/cjun357/lab-manual)) will automatically be added to this pull request.  Then, when I merge your pull request, both the `lab_manual.tex` and `lab_manual.pdf` files will be updated with your changes.

Again, feel free to email me or message me on Slack if you have any questions or get stuck!

**Pull request merged**
